// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {main} from '../models';
import {tunnel} from '../models';

export function CheckCloudflaredUpdate():Promise<Record<string, string>>;

export function CreateTunnel(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean):Promise<db.Tunnel>;

export function DeleteTunnel(arg1:number):Promise<void>;

export function GetAllStatuses():Promise<Record<number, main.TunnelStatus>>;

export function GetCloudflaredVersion():Promise<string>;

export function GetSetting(arg1:string):Promise<string>;

export function GetTunnelLogs(arg1:number):Promise<Array<string>>;

export function GetTunnelMetrics(arg1:number):Promise<tunnel.Metrics>;

export function GetTunnelStatus(arg1:number):Promise<main.TunnelStatus>;

export function GetTunnels():Promise<Array<db.Tunnel>>;

export function InstallCloudflared():Promise<void>;

export function IsAutoStartEnabled():Promise<boolean>;

export function IsCloudflaredInstalled():Promise<boolean>;

export function OpenURL(arg1:string):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function StartTunnel(arg1:number):Promise<void>;

export function StopTunnel(arg1:number):Promise<void>;

export function UpdateCloudflared():Promise<void>;

export function UpdateTunnel(arg1:number,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string,arg7:string,arg8:string,arg9:boolean):Promise<void>;
