// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckCloudflaredUpdate() {
  return window['go']['main']['App']['CheckCloudflaredUpdate']();
}

export function CreateAccess(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateAccess'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateTunnel(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['CreateTunnel'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function DeleteAccess(arg1) {
  return window['go']['main']['App']['DeleteAccess'](arg1);
}

export function DeleteTunnel(arg1) {
  return window['go']['main']['App']['DeleteTunnel'](arg1);
}

export function GetAccessLogs(arg1) {
  return window['go']['main']['App']['GetAccessLogs'](arg1);
}

export function GetAccessStatus(arg1) {
  return window['go']['main']['App']['GetAccessStatus'](arg1);
}

export function GetAccesses() {
  return window['go']['main']['App']['GetAccesses']();
}

export function GetAllAccessStatuses() {
  return window['go']['main']['App']['GetAllAccessStatuses']();
}

export function GetAllStatuses() {
  return window['go']['main']['App']['GetAllStatuses']();
}

export function GetCloudflaredVersion() {
  return window['go']['main']['App']['GetCloudflaredVersion']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetTunnelLogs(arg1) {
  return window['go']['main']['App']['GetTunnelLogs'](arg1);
}

export function GetTunnelMetrics(arg1) {
  return window['go']['main']['App']['GetTunnelMetrics'](arg1);
}

export function GetTunnelStatus(arg1) {
  return window['go']['main']['App']['GetTunnelStatus'](arg1);
}

export function GetTunnels() {
  return window['go']['main']['App']['GetTunnels']();
}

export function InstallCloudflared() {
  return window['go']['main']['App']['InstallCloudflared']();
}

export function IsAutoStartEnabled() {
  return window['go']['main']['App']['IsAutoStartEnabled']();
}

export function IsCloudflaredInstalled() {
  return window['go']['main']['App']['IsCloudflaredInstalled']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ScanLAN(arg1) {
  return window['go']['main']['App']['ScanLAN'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function StartAccess(arg1) {
  return window['go']['main']['App']['StartAccess'](arg1);
}

export function StartTunnel(arg1) {
  return window['go']['main']['App']['StartTunnel'](arg1);
}

export function StopAccess(arg1) {
  return window['go']['main']['App']['StopAccess'](arg1);
}

export function StopTunnel(arg1) {
  return window['go']['main']['App']['StopTunnel'](arg1);
}

export function UpdateAccess(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateAccess'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UpdateCloudflared() {
  return window['go']['main']['App']['UpdateCloudflared']();
}

export function UpdateTunnel(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['UpdateTunnel'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}
